version: '3.8'

services:

  prism-nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - prism-php
      - prism-node
      - prism-redis
      - prism-memcached
      - prism-pgsql
      - prism-mailhog
    restart: "always"

  prism-php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    expose:
      - 9000
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    restart: "always"

  prism-node:
    build:
      context: ./docker
      dockerfile: node.dockerfile
    restart: "always"

  prism-redis:
    build:
      context: ./docker
      dockerfile: redis.dockerfile
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./docker/volumes/redis:/var/lib/redis
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: "always"

  prism-memcached:
    build:
      context: ./docker
      dockerfile: memcached.dockerfile
    restart: "always"

  prism-pgsql:
    build:
      context: ./docker
      dockerfile: pgsql.dockerfile
    ports:
      - '5432:5432'
    restart: "always"
    environment:
      PGPASSWORD: 'secret'
      POSTGRES_DB: 'prism'
      POSTGRES_USER: 'prism'
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - './docker/volumes/pgsql:/var/lib/postgresql/data'

  prism-mailhog:
    build:
      context: ./docker
      dockerfile: mailhog.dockerfile
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: "always"
