version: '3.8'

services:

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    container_name: 'prism-nginx'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
      - node
      - pgsql
      - mailhog

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    container_name: 'prism-php'
    expose:
      - 9000
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www

  node:
    build:
      context: ./docker
      dockerfile: node.dockerfile
    container_name: 'prism-node'

  redis:
    build:
      context: ./docker
      dockerfile: redis.dockerfile
    container_name: 'prism-redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./docker/volumes/redis:/var/lib/redis
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  memcached:
    build:
      context: ./docker
      dockerfile: memcached.dockerfile
    container_name: 'prism-memcached'

  pgsql:
    build:
      context: ./docker
      dockerfile: pgsql.dockerfile
    container_name: 'prism-pgsql'
    ports:
      - '5432:5432'
    environment:
      PGPASSWORD: 'secret'
      POSTGRES_DB: 'prism'
      POSTGRES_USER: 'prism'
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - './docker/volumes/pgsql:/var/lib/postgresql/data'

  mailhog:
    build:
      context: ./docker
      dockerfile: mailhog.dockerfile
    container_name: 'prism-mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
